// frontend/src/components/Header.jsx
import React from 'react';

const Header = () => {
  return (
    <header style={{
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: '0.75rem 2rem',
      backgroundColor: 'var(--color-white)',
      borderBottom: '1px solid var(--color-border)',
      boxShadow: '0 2px 4px rgba(0,0,0,0.05)'
    }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
        <div style={{
          width: '32px',
          height: '32px',
          backgroundColor: 'var(--color-primary)',
          borderRadius: '50%',
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          color: 'var(--color-white)',
          fontWeight: 'bold',
          fontSize: '12px'
        }}>
          PI
        </div>
        <h1 style={{ margin: 0, fontSize: '1.2rem', color: 'var(--color-primary)' }}>
          Termo Fácil
        </h1>
      </div>

      <div style={{ display: 'flex', alignItems: 'center', gap: '2rem', fontSize: '0.9rem' }}>
        <div>
          Status: <span className="text-success">VPN Segura</span>
        </div>
        <div>
          Policial: <strong>João Silva</strong>
        </div>
      </div>
    </header>
  );
};

export default Header;

// frontend/src/app/components/header/header.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-header',
  standalone: true,
  templateUrl: './header.component.html'
})
export class HeaderComponent {
  title = 'Termo Fácil';
  user = 'Escrivão Silva';
  station = '1ª DP - Teresina/PI';
}

<header style="background-color: var(--color-primary); color: var(--color-white); padding: 1rem 2rem; display: flex; justify-content: space-between; align-items: center; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
  <div style="display: flex; align-items: center; gap: 1rem;">
    <div style="font-size: 1.5rem; font-weight: bold; letter-spacing: 1px;">
      🛡️ {{ title }}
    </div>
    <div style="font-size: 0.8rem; background-color: var(--color-accent); padding: 2px 6px; border-radius: 4px; font-weight: bold;">
      MVP SSP-PI
    </div>
  </div>
  
  <div style="display: flex; align-items: center; gap: 1.5rem; font-size: 0.9rem;">
    <div>
      <span style="opacity: 0.8;">Unidade:</span> <strong>{{ station }}</strong>
    </div>
    <div style="display: flex; align-items: center; gap: 0.5rem;">
      <div style="width: 32px; height: 32px; background-color: var(--color-white); color: var(--color-primary); border-radius: 50%; display: flex; align-items: center; justify-content: center; font-weight: bold;">
        ES
      </div>
      <span>{{ user }}</span>
    </div>
  </div>
</header>
