// frontend/src/app/app.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HeaderComponent } from './components/header/header.component';
import { AuditoriaComponent } from './components/auditoria/auditoria.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, HeaderComponent, AuditoriaComponent],
  templateUrl: './app.component.html'
})
export class AppComponent {
  title = 'frontend';
}

<div class="container-fluid">
  <app-header></app-header>
  <app-auditoria></app-auditoria>
</div>

// frontend/src/App.jsx
import React from 'react';
import Header from './components/Header';
import AudioPlayer from './components/AudioPlayer';
import Auditoria from './pages/Auditoria';

function App() {
  return (
    <div className="container-fluid">
      <Header />
      <AudioPlayer />
      <Auditoria />
    </div>
  );
}

export default App;
